# Generated by Django 2.2.6 on 2019-10-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
