# Generated by Django 2.2.6 on 2019-10-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191023_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner_id',
            new_name='ownerId',
        ),
    ]
