# Generated by Django 2.2.6 on 2019-10-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191023_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ownerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars_owner', to='store.Owner', verbose_name='Owner'),
        ),
    ]
